### PR TITLE
Fixed an access level to subscriptions

### PR DESCRIPTION
**Pull request by tayadelmar**
**The issue:** in `cmd/gen/main.go` the `subscriptionTemplate` was hard coded only with public access to any subscription, but some of them has a private access.

**Solution:** Added `AccessLevel` to distinguish public and private subscriptions.

Also on master branch: a decode fails to most of subscriptions with error: 
```bash
RPC Error: error decoding notification: a slice, expected a map
```  
the error is coming from here:
```go
if err := mapstructure.Decode(n.Params.Data, &ret); err != nil {
					e.errors <- fmt.Errorf("error decoding notification: %s", err)
				}
```
and it occurs, because  `n.Params.Data` is json.RawMessage, i.e. slice of byte. And even if I unmarshal json.RawMessage to map[string]interface{} before,  `mapstructure` skips some fields while decoding.

But anyway, your initial template had the std lib json.Unmarshal which is working fine.

### CODE REVIEW

**Comment by tayadelmar** [comment]
There is one thing more: depends on a frequency of notifications the api returns different response:

"100ms": 
```json
[{"time_in_force":"good_til_cancelled","reduce_only":false,"profit_loss":0.0,"price":55.5,"post_only":false,"order_type":"limit","order_state":"open","order_id":"2469894408","max_show":10,"last_update_timestamp":1560374905491,"label":"","is_liquidation":false,"instrument_name":"BTC-PERPETUAL","filled_amount":0,"direction":"buy","creation_timestamp":1560374905491,"commission":0.0,"average_price":0.0,"api":true,"amount":10}]
```

"raw":
```json
{"time_in_force":"good_til_cancelled","reduce_only":false,"profit_loss":0.0,"price":55.5,"post_only":false,"order_type":"limit","order_state":"open","order_id":"2469912002","max_show":10,"last_update_timestamp":1560375377497,"label":"","is_liquidation":false,"instrument_name":"BTC-PERPETUAL","filled_amount":0,"direction":"buy","creation_timestamp":1560375377497,"commission":0.0,"average_price":0.0,"api":true,"amount":10}
```

The current PR is working with "raw" frequency, but I will try to add a fix for this tomorrow.

**Review by adampointer-form3 — APPROVED** [review]
LGTM - thanks for your contribution

**Comment by tayadelmar** [comment]
I added a fix to notifications unmarshal to distinguish incoming json object and json array, so I suppose it should work with any kind of a frequency of notifications, but I checked only with "raw" and "100ms" for the `user.orders` subscription.

It makes sense to send an array of updates through, because for "100ms" could appear more than one order update.

**Comment by adampointer** [comment]
Ok I see what you mean. The API is kind of nasty with it's mixing of slices and objects for the same key. I ended up using json.RawMessage to defer decoding until we could better infer the type. This solution works for the notifications. I guess it would be nice to add some tests, I have been a bit lazy there! There is for example `nock` which might work for mocking responses on the websocket.

I will open an issue for better testing. Also I need to keep on at the Deribit devs to publish an up to date and valid schema as we are missing some methods.

**Pull request merged**
