### PR TITLE
add cancel by label

### PR DESCRIPTION
**Pull request by kprimice**
Adding https://docs.deribit.com/v2/#private-cancel_by_label

I couldn't generate the code with swagger. Can someone help with that?

### CODE REVIEW

**Comment by adampointer** [comment]
Hi sorry for the late reply. Run `make generate-client` and `make generate-models`

**Comment by kprimice** [comment]
It does not work for whatever reason...

**Comment by adampointer** [comment]
I just tried it and it is ok. Did you run make in the v3 directory? What errors or behaviour are you seeing exactly?

**Comment by kprimice** [comment]
@adampointer swagger generates client code in ./client instead of ./client/v3

(Also the Makefile does not find swagger I have to copy/paste the swagger command line manually in the terminal)

**Comment by adampointer** [comment]
Hey. Sounds like you need to cd to `v3` and run make there. I should make this clear in the Readme

**Comment by kprimice** [comment]
That is what I did!

**Comment by adampointer** [comment]
Oh! Ok what we do is merge this and then I will generate the code on my MacBook for you and investigate fixing the build scripts. It will be a couple of days as New Year is approaching and I won't be sober lol

**Comment by kprimice** [comment]
Thank you so much @adampointer and I hope you had a great time for NYE :)

**Pull request merged**
