### PR TITLE
Fixed reconnect

### PR DESCRIPTION
**Pull request by tayadelmar**
Observed some issues by using a current reconnect:
 - disability to reconnect a client, which wasn't authenticated, i.e. subscribed only to public channels.
 - a cause reconnect from a go routine with a ticker, it's a wrong approach, because every caused reconnect doesn't know about the others. It may lead to collisions and errors.
 - a pinging a connection withing a rest request each 10 sec, which creates unnecessary load on the client usage. 
- reconnect should be called only from one place, a reading error is a right place, because the reading loop go routine will be gracefully terminated.  

Used the gorilla wesocket pinging to fix those issues.

Added OnConnect callback to the RPCCore, to allow user to renew a state of an application after reconnect, or to put any logic there, which should be done immediately after reconnect.

### CODE REVIEW

**Comment by adampointer** [comment]
Hi. Sorry for my slowness. I have invited you to collaborate on this project.

**Comment by adampointer** [comment]
Build is failing..

```
/exchange.go:132:15: Errorf format %w has unknown verb w
```

**Comment by tayadelmar** [comment]
Hi! Thank you so much for the invitation! 

It's a new feature in go1.13 release : https://golang.org/doc/go1.13#error_wrapping

I just decided to play with it, but it can be easily removed. Anyway, it would be better to build with the latest go releases, no?

**Comment by adampointer** [comment]
If we are using go 1.13 features then you need to add a note in the README to say so. Also change the version in travis.yml so the build passes. Other than that, I am happy.

**Pull request merged**
